# Training configuration
dataset:
  name: "FashionMNIST"
  batch_size: 128
  num_workers: 16

training:
  epochs: 10
  learning_rate: 0.001
  optimizer:
    type: "Adam"
    betas: [0.9, 0.999]
  scheduler:
    type: "ReduceLROnPlateau"
    patience: 3
    factor: 0.1

