# Model architecture configuration
model_name: "ConvolutionalAutoencoder"
input_channels: 1  # MNIST=1, CIFAR=3
architecture:
  encoder:
    - layer1:
        type: "Conv2d"
        out_channels: 16
        kernel_size: 5
        stride: 2
        padding: 2
        batch_norm: true
    - layer2:
        type: "Conv2d"
        out_channels: 32
        kernel_size: 5
        stride: 2
        padding: 2
        batch_norm: true
    - layer3:
        type: "Conv2d"
        out_channels: 64
        kernel_size: 7
        padding: 3
        batch_norm: true
  decoder:
    - layer1:
        type: "ConvTranspose2d"
        out_channels: 32
        kernel_size: 7
        padding: 3
        batch_norm: true
    - layer2:
        type: "ConvTranspose2d"
        out_channels: 16
        kernel_size: 5
        stride: 2
        padding: 2
        output_padding: 1
        batch_norm: true
    - layer3:
        type: "ConvTranspose2d"
        out_channels: 1  # Match input_channels
        kernel_size: 5
        stride: 2
        padding: 2
        output_padding: 1
        activation: "sigmoid"